services:
  postgres:
    image: postgres:15
    container_name: meal-planner-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mealplanner
      POSTGRES_PASSWORD: Walrusp1t69!
      POSTGRES_DB: meal_planner
    volumes:
      - ./pgdata:/var/lib/postgresql/data
